server:
  port: 7002



eureka:
  instance:
    hostname: eureka02.com
  client:
    register-with-eureka: false # 表示eureka不会自己注册自己
    service-url:
      # 与euraka交互的地址
      defaultZone: http://eureka01.com:7001/eureka

